"""Initial migration-2

Revision ID: 0247718ee138
Revises: 25ea9bb297dd
Create Date: 2024-09-17 18:35:18.228844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0247718ee138'
down_revision: Union[str, None] = '25ea9bb297dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('additional_files')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_files', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
