"""Initial migration

Revision ID: 89ebe864f393
Revises: 
Create Date: 2024-09-14 22:41:28.133997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ebe864f393'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id_user'), ['id_user'], unique=False)

    op.create_table('projects',
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_project')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id_project'), ['id_project'], unique=False)

    op.create_table('additional_files',
    sa.Column('id_additional_file', sa.Integer(), nullable=False),
    sa.Column('file_description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_additional_file')
    )
    with op.batch_alter_table('additional_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_additional_files_id_additional_file'), ['id_additional_file'], unique=False)

    op.create_table('author_info',
    sa.Column('id_author_info', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('functionality_description', sa.Text(), nullable=False),
    sa.Column('registration_address', sa.String(), nullable=False),
    sa.Column('resume_path', sa.String(), nullable=True),
    sa.Column('video_link', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_author_info')
    )
    with op.batch_alter_table('author_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_info_id_author_info'), ['id_author_info'], unique=False)

    op.create_table('expenses',
    sa.Column('id_expense', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('expense_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_expense')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_id_expense'), ['id_expense'], unique=False)

    op.create_table('general_info',
    sa.Column('id_general_info', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('project_title', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('contacts', sa.Text(), nullable=False),
    sa.Column('implementation_scale', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_general_info')
    )
    with op.batch_alter_table('general_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_info_id_general_info'), ['id_general_info'], unique=False)

    op.create_table('media_resources',
    sa.Column('id_media_resource', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('publication_month', sa.String(), nullable=False),
    sa.Column('planned_views', sa.Integer(), nullable=False),
    sa.Column('resource_links', sa.Text(), nullable=False),
    sa.Column('chosen_format_reason', sa.Text(), nullable=False),
    sa.Column('media_plan_path', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_media_resource')
    )
    with op.batch_alter_table('media_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_resources_id_media_resource'), ['id_media_resource'], unique=False)

    op.create_table('mentors',
    sa.Column('id_mentor', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('resume_path', sa.String(), nullable=True),
    sa.Column('competencies', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_mentor')
    )
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentors_id_mentor'), ['id_mentor'], unique=False)

    op.create_table('own_funds',
    sa.Column('id_own_fund', sa.Integer(), nullable=False),
    sa.Column('expense_list', sa.Text(), nullable=False),
    sa.Column('amount_rub', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_own_fund')
    )
    with op.batch_alter_table('own_funds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_own_funds_id_own_fund'), ['id_own_fund'], unique=False)

    op.create_table('partner_supports',
    sa.Column('id_partner_support', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(), nullable=False),
    sa.Column('support_type', sa.String(), nullable=False),
    sa.Column('expense_list', sa.Text(), nullable=False),
    sa.Column('amount_rub', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_partner_support')
    )
    with op.batch_alter_table('partner_supports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_supports_id_partner_support'), ['id_partner_support'], unique=False)

    op.create_table('project_details',
    sa.Column('id_project_details', sa.Integer(), nullable=False),
    sa.Column('brief_info', sa.Text(), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('target_groups', sa.Text(), nullable=False),
    sa.Column('main_goal', sa.Text(), nullable=False),
    sa.Column('successful_experiences', sa.Text(), nullable=False),
    sa.Column('development_perspectives', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_project_details')
    )
    with op.batch_alter_table('project_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_details_id_project_details'), ['id_project_details'], unique=False)

    op.create_table('project_geography',
    sa.Column('id_project_geography', sa.Integer(), nullable=False),
    sa.Column('region_or_district', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_project_geography')
    )
    with op.batch_alter_table('project_geography', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_geography_id_project_geography'), ['id_project_geography'], unique=False)

    op.create_table('project_results',
    sa.Column('id_project_result', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.DateTime(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('event_unit', sa.String(), nullable=False),
    sa.Column('last_event_date', sa.DateTime(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('participant_unit', sa.String(), nullable=False),
    sa.Column('publication_count', sa.Integer(), nullable=False),
    sa.Column('publication_unit', sa.String(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('view_unit', sa.String(), nullable=False),
    sa.Column('social_effect', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_project_result')
    )
    with op.batch_alter_table('project_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_results_id_project_result'), ['id_project_result'], unique=False)

    op.create_table('reviews',
    sa.Column('id_review', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('team_experience', sa.SmallInteger(), nullable=False),
    sa.Column('project_relevance', sa.SmallInteger(), nullable=False),
    sa.Column('solution_uniqueness', sa.SmallInteger(), nullable=False),
    sa.Column('implementation_scale', sa.SmallInteger(), nullable=False),
    sa.Column('development_potential', sa.SmallInteger(), nullable=False),
    sa.Column('project_transparency', sa.SmallInteger(), nullable=False),
    sa.Column('feasibility_and_effectiveness', sa.SmallInteger(), nullable=False),
    sa.Column('additional_resources', sa.SmallInteger(), nullable=False),
    sa.Column('planned_expenses', sa.SmallInteger(), nullable=False),
    sa.Column('budget_realism', sa.SmallInteger(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_review')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_id_review'), ['id_review'], unique=False)

    op.create_table('task_events',
    sa.Column('id_task_event', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('unique_participants', sa.Integer(), nullable=False),
    sa.Column('repeating_participants', sa.Integer(), nullable=False),
    sa.Column('publication_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_task_event')
    )
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_events_id_task_event'), ['id_task_event'], unique=False)

    op.create_table('team_members',
    sa.Column('id_team_member', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('resume_path', sa.String(), nullable=True),
    sa.Column('competencies', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id_project'], ),
    sa.PrimaryKeyConstraint('id_team_member')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_id_team_member'), ['id_team_member'], unique=False)

    op.create_table('other_additional_files',
    sa.Column('id_file', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_link', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['general_info.project_id'], ),
    sa.PrimaryKeyConstraint('id_file')
    )
    with op.batch_alter_table('other_additional_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_other_additional_files_id_file'), ['id_file'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('other_additional_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_other_additional_files_id_file'))

    op.drop_table('other_additional_files')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_id_team_member'))

    op.drop_table('team_members')
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_events_id_task_event'))

    op.drop_table('task_events')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_id_review'))

    op.drop_table('reviews')
    with op.batch_alter_table('project_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_results_id_project_result'))

    op.drop_table('project_results')
    with op.batch_alter_table('project_geography', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_geography_id_project_geography'))

    op.drop_table('project_geography')
    with op.batch_alter_table('project_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_details_id_project_details'))

    op.drop_table('project_details')
    with op.batch_alter_table('partner_supports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_supports_id_partner_support'))

    op.drop_table('partner_supports')
    with op.batch_alter_table('own_funds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_own_funds_id_own_fund'))

    op.drop_table('own_funds')
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentors_id_mentor'))

    op.drop_table('mentors')
    with op.batch_alter_table('media_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_resources_id_media_resource'))

    op.drop_table('media_resources')
    with op.batch_alter_table('general_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_info_id_general_info'))

    op.drop_table('general_info')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_id_expense'))

    op.drop_table('expenses')
    with op.batch_alter_table('author_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_info_id_author_info'))

    op.drop_table('author_info')
    with op.batch_alter_table('additional_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_additional_files_id_additional_file'))

    op.drop_table('additional_files')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id_project'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id_user'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
